export const AUTH_TOKENS = {
  USER_REPOSITORY: Symbol('USER_REPOSITORY'),
  HASHING_SERVICE: Symbol('HASHING_SERVICE'),
  TOKEN_SERVICE: Symbol('TOKEN_SERVICE'),
  OTP_SERVICE: Symbol('OTP_SERVICE'),
  PASSWORD_RESET_SERVICE: Symbol('PASSWORD_RESET_SERVICE'),
  EMAIL_SERVICE: Symbol('EMAIL_SERVICE'),
  SESSION_STORE: Symbol('SESSION_STORE'),
};
